runtime: nodejs
env: flex

env_variables:
  GA_TRACKING_ID: UA-97880882-3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

endpoints_api_service:
  name: nth-rarity-204509.du.r.appspot.com
  rollout_strategy: managed

readiness_check:
  app_start_timeout_sec: 1000
