name: CI/CD to Seonglae Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  make-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install npm dependencies
      run: yarn

    - name: Run build task
      run: yarn build

    - uses: actions/upload-artifact@v1
      with:
        name: make artiface
        path: public

  depolyment:
    needs: make-artifact
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/react
          git pull
          yarn
          yarn build
